[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
image = "0.23.14"
bvh = "0.7.2"

[profile.dev]
opt-level = 3              # Use slightly better optimizations.