name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Change to the Rust project directory
    - name: Change to Rust project directory
      run: cd twobounce-rust

    # Build the project and place the executable in the root directory
    - name: Build
      run: cargo build --verbose --target-dir ../

    # Run tests
    - name: Run tests
      run: cargo test --verbose
